name: Generate Composer Lock

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: composer:v2

    - name: Run Composer Update
      run: |
        composer update --no-interaction > composer_error.txt 2>&1 || true
        cat composer_error.txt

    - name: Commit error log
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add composer_error.txt composer.lock || true
        git commit -m "chore: add composer log" || echo "No changes"
        git push

